export const TRUTHY = "1";

export const PERMISSION_TYPES = {
  CAMERA: "CAMERA",
  LOCATION_FINE: "ACCESS_FINE_LOCATION",
  LOCATION_COARSE: "ACCESS_COARSE_LOCATION",
  READ_FILE: "READ_EXTERNAL_STORAGE",
  WRITE_FILE: "WRITE_EXTERNAL_STORAGE",
};
